### ISSUE TITLE
Filter box section popping up slow

### ISSUE THREAD

**Issue by jgingh7** [gcivil-nyu-org/nycCivilServiceJobs#123]
## Expected Behavior

The page finishes loading within 1 second.
If not, each "section" should be loaded within 1 second after some section is loaded.
If not, there should be a spinner icon indicating something will be popped up at that place.

## Current Behavior

![image](https://user-images.githubusercontent.com/60978943/100157000-df767380-2e77-11eb-9c82-7469ca07b6e3.png)
(I'm not sure if it is just me)
The filter box shows up 3 seconds after the page finishes loading.
(What I mean by "finish loading" here is that the below icon is no more a spinner)
![image](https://user-images.githubusercontent.com/60978943/100157554-bc988f00-2e78-11eb-94f6-3c5c2c7d4ba1.png)

## Steps to Reproduce

1.
2.
3.
4.

**Comment by gsavitha** [comment]
Not a bug. This is expected behaviour. We intentionally load filters section after the job results are loaded.
