### ISSUE TITLE
SUGGESTION Reset button for the filter

### ISSUE THREAD

**Issue by jgingh7** [gcivil-nyu-org/nycCivilServiceJobs#124]
Maybe a reset button for the filter might be helpful.
Right now I have to reload the page to do that.
![image](https://user-images.githubusercontent.com/60978943/100157839-40527b80-2e79-11eb-9b22-6a50c681ffb4.png)

**Comment by joshganguly** [comment]
Thanks for this enhancement suggestion. This is something we have kept in mind for icebox.

**Comment by i-rahman** [comment]
was accidentally closed!
