### ISSUE TITLE
Duplicates in Agency drop-down filter

### ISSUE THREAD

**Issue by rossy312** [gcivil-nyu-org/nycCivilServiceJobs#126]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

After entering a keyword in the Jobs search, duplicates are created in the agency filter.

## Expected Behavior
I expected the Agency filter drop-down to list distinct city agencies, to help refine my search. 

## Current Behavior
The Agency filter drop-down listed NYC Housing Authority (NYCHA) and Housing Preservation and Development (HPD) multiple times over and over.

## Ideas for Improvement
When a keyword has already reduced the search, the Agency filter should only list the associated city agency one time.

## Steps to Reproduce
1. I clicked on the Jobs button.
2. I entered "housing" in the Search bar.
3. I clicked on the Agency filter drop-down.

## Context (Environment)
This isn't a huge deal, but to someone who is unfamiliar with city agencies, it could be confusing to see the same agency listed multiple times in the drop-down menu.
![Screen Shot 2020-11-24 at 8 59 44 PM](https://user-images.githubusercontent.com/69653730/100173398-6c312980-2e98-11eb-85a2-5ab2f50f7554.png)

**Comment by i-rahman** [comment]
Thank you @rossy312  for finding this bug. We accidentality broke it yesterday.

**Comment by shivangpandya** [comment]
Fixed the issue and pushed in staging
