### ISSUE TITLE
Able to enter invalid birthday

### ISSUE THREAD

**Issue by rossy312** [gcivil-nyu-org/nycCivilServiceJobs#127]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

I was able to enter a birthday of December 4, 1000. 

## Expected Behavior
I expected a limit to be placed on the year of birth. 

## Current Behavior
No restrictions on the year of birth. 

## Ideas for Improvement
I would suggest restricting the birth year to 1900. 

## Steps to Reproduce
1. I went to the User profile. 
2. I edited the Date of Birth.
3. I clicked Updated Profile.

## Context (Environment)
This is a minor issue of course, but does allow users to select completely invalid birth dates, which could undermine the credibility of the site ever so slightly. 
![Screen Shot 2020-11-24 at 9 07 26 PM](https://user-images.githubusercontent.com/69653730/100173918-756ec600-2e99-11eb-8376-9606e299029b.png)

**Comment by gauravag2207** [comment]
Hi @rossy312  ,

Thank you for pointing this out but this validation is not been put yet and the same is mentioned in the testing guide as well. So I suppose this would not be a bug. We will certainly take this as an enhancement 
![image](https://user-images.githubusercontent.com/55005259/100268343-7a278e80-2f1a-11eb-90a3-3788b587718c.png)
