### ISSUE TITLE
It takes longer time when users try to find all jobs.

### ISSUE THREAD

**Issue by Huanjin-Zhang** [gcivil-nyu-org/nycCivilServiceJobs#128]
## Expected Behavior
When users try to find all jobs by simply clicking on "search" under the "job" tab. It should show all the information ASAP.

## Current Behavior
For now, it will take a longer time to load filters than I expect if there are lots of data(in this case, 656 jobs). Also, it takes some time to reload the result after clicking on the sort function.

## Ideas for Improvement.
It may be better to redesign the method to get the data or something else.

## Steps to Reproduce
1. I click the search under "Job" tab.
2. I click other sorting functions.

## Context (Environment)
![image](https://user-images.githubusercontent.com/55302047/100179562-5295df00-2ea4-11eb-9171-d5ad56353858.png)

**Comment by gsavitha** [comment]
Longer load time is due to large number of jobs being loaded. Added Pagination to fix this issue.  Deployed to staging,
