### ISSUE TITLE
Responsiveness issue on landing page

### ISSUE THREAD

**Issue by ronakf11** [gcivil-nyu-org/nycCivilServiceJobs#130]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

When I make the width of webpage smaller, the line "We have 655 great civil service jobs for you!" is hideen behing the navbar.

## Expected Behavior

The display of website and content should both be responsive.

## Current Behavior

Currently the container div on landing page hides partially behind navbar on testing for responsiveness

## Ideas for Improvement

Can be due to no overflow set in CSS for particular section.

## Steps to Reproduce

1. Go to landing page (I am using browser Google Chrome)
2. Press F12 for chrome dev tools for checking responsiveness or manually adjust the width of page.
3. Adjust width to 510px specifically.
4.

## Context (Environment)

This issue can be sorted by updating CSS for on basis of screen width and applying overflow or manually adding padding or margin according to specific needs.

**Comment by gauravag2207** [comment]
HI @ronakf11 ,

We had already discussed this with the professor and responsiveness (mobile, tablet) of the website is not something that should be focused for testing.

**Comment by shivangpandya** [comment]
@ronakf11 Closing this as the scope of the project is Web Application for Desktop Browsers
