### ISSUE TITLE
Duplicate values in filter/Multiple results with same JOB ID

### ISSUE THREAD

**Issue by ronakf11** [gcivil-nyu-org/nycCivilServiceJobs#131]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

When I try to filter using agency, there are multiple options for agency "ADMIN FOR CHILDREN'S SVCS" and when i search for the same i get multiple jobs with same job id.

## Expected Behavior

Data should be consistent and should be processed to delete duplicate or inconsistent values.

## Current Behavior

Currently duplicate values are present in filter for agency and duplicate results are fetched with same id showing no check for duplicate values.

## Ideas for Improvement

Can either process the database beforehand or run check for duplicate values in backend before displaying data.

## Steps to Reproduce

1. Go to jobs
2. In agency filter, search for "ADMIN FOR CHILDREN'S SVCS"  [BUG]
3. Results show multiple jobs with same id probably because of the duplicate values in database [BUG]

## Context (Environment)

In real-time, such inconsistency can misguide user and should be checked either in backend before displaying data or the database should be processed.

![1](https://user-images.githubusercontent.com/60564034/100272596-711dd800-2f81-11eb-87e0-5e55038a4cd9.PNG)
![2](https://user-images.githubusercontent.com/60564034/100272598-724f0500-2f81-11eb-9d54-d7c9bb2ce2de.PNG)
![3](https://user-images.githubusercontent.com/60564034/100272600-724f0500-2f81-11eb-8eb8-c60050ba16aa.PNG)

**Comment by ronakf11** [comment]
**SUGGESTION**
Having a reset button is better for UX and better overall filter functionality.

**Comment by gauravag2207** [comment]
Hi @ronakf11 ,

We have identified this bug with duplicate values in Filters, #126 
For 2 results for same job id, that if you notice one job is **external** and one is **internal**. This is how it comes from NYC open data. 
![image](https://user-images.githubusercontent.com/55005259/100272822-63d10100-2f21-11eb-9c89-c2c54967b24a.png)

If you find exact same jobs, please let us know and provide a screenshot.

**Comment by shivangpandya** [comment]
Tracked under #126 , so closing the issue
