### ISSUE TITLE
Clicking on search button on page JOB without any query causes loading delay

### ISSUE THREAD

**Issue by ronakf11** [gcivil-nyu-org/nycCivilServiceJobs#132]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

Doing so fetched all results which is understandable but it takes very long to load all the data on a single page which shouldn't be the case.

## Expected Behavior

Pages should not take take time in loading.

## Current Behavior

Currently when i click search without any input fetched all results leading the page to load very slowly.

## Ideas for Improvement

This might be because of the way of fetching details on page such as doing API Calls for results, Can be fixed by storing the data in database and having a scheduler to call the API in every span of a time to update the data.

## Steps to Reproduce

1. Go to JOBS page
2. Hit search without any input
3.
4.

## Context (Environment)

As a user, it's very reasonable that people might hit search without any input by mistake or on purpose in real-time whcih causes delay in page loading leading to bad UX.

**Comment by gsavitha** [comment]
Marked as duplicate. Identified in #128

**Comment by ronakf11** [comment]
Any filter/sort applied to the page with all the results will cause delay or might also hang slow systems.
