### ISSUE TITLE
<Suggestion>Can not get email notification for saved jobs

### ISSUE THREAD

**Issue by Chuanqi927** [gcivil-nyu-org/nycCivilServiceJobs#133]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

**JUST A SUGGESTION**
For this test party, we can not get email notification because your scheduler is set to send email on morning, said in your test guide. So I can not test this feature, which I think is important, for this test party until tomorrow morning. Maybe you should make the scheduler more frequent just for this testing purpose. XD 

## Expected Behavior
I will get email notification

## Current Behavior
Have to wait until next day to check

## Ideas for Improvement
Make scheduler for sending email more frequent
## Steps to Reproduce
1. Follow the Test Data section in test guide

## Context (Environment)
I can not test this feature until next day. Really willing to see that.

**Comment by i-rahman** [comment]
Hi @Edward0o0 we can run manually run it for you at 7:30pm if you want to test it. Just add the Exam ID for Exam result, Civil Service Title for Upcoming Exam and Save the Jobs prior to that.

**Comment by gauravag2207** [comment]
Adding to that, please add the jobs which have a deadline within the next 2 days.

**Comment by Chuanqi927** [comment]
Ok. Very much appreciated. Thank you

> Hi @Edward0o0 we can run manually run it for you at 7:30pm if you want to test it. Just add the Exam ID for Exam result, Civil Service Title for Upcoming Exam and Save the Jobs prior to that.

**Comment by i-rahman** [comment]
@Edward0o0 Please also make sure to update your email in the profile

**Comment by joshganguly** [comment]
https://gcivil-nyu.slack.com/archives/CMUSHCS9M/p1606351076161700?thread_ts=1606350593.160000&cid=CMUSHCS9M Thank you for confirming that you have received these email notifications. We are closing this ticket.
