### ISSUE TITLE
Suggestion: Email should only be able to updated after getting registration link again

### ISSUE THREAD

**Issue by leelightman** [gcivil-nyu-org/nycCivilServiceJobs#134]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

When I update the email address in the account profile, the profile is able to be updated successfully without resending an email activation link.

## Steps to Reproduce

1. Account Details
2. Profile
3. Update email
4.

**Comment by gauravag2207** [comment]
Thank you @leelightman . We are not doing it right now as we don't have the email verification process in place while registration which was a collaborative team decision. We can certainly take this as an enhancement and implement when we implement that.

**Comment by joshganguly** [comment]
duplicate of #122

**Comment by shivangpandya** [comment]
Tracked under #122  , so closing the issue
