### ISSUE TITLE
Allow number as First/Last name in Account profile

### ISSUE THREAD

**Issue by leelightman** [gcivil-nyu-org/nycCivilServiceJobs#135]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

When I update the profile on the account details page, numbers are allowed as input
## Steps to Reproduce

1. Account details
2. profile
3. Update first/ last name
4.

**Comment by gauravag2207** [comment]
Hi @leelightman , This was intentional as people can have numbers in their names. Most of the websites allow it. Even Gmail

![image](https://user-images.githubusercontent.com/55005259/100293747-50865b80-2f4a-11eb-8d5a-91e34943c342.png)

**Comment by shivangpandya** [comment]
As Gaurav commented, this is an intended implementation so closing it
