### ISSUE TITLE
Suggestion: underline/ mark words with tooltip explanation

### ISSUE THREAD

**Issue by leelightman** [gcivil-nyu-org/nycCivilServiceJobs#136]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

When hovering over certain words, the tooltip explanation will pop up. However, it will be more clear if there are dotted underlines for these words.

## Steps to Reproduce

1. Under the Jobs tab
2. In "Exterminator"
3. hover "Competitive" for Title Classification: Competitive
4.

**Comment by gauravag2207** [comment]
Hi @leelightman , we can consider this as an enhancement based on the timeline. Thank you for this.

**Comment by shivangpandya** [comment]
The team has made a UI decision not to add this to the UI as it will clutter the current UI
