### ISSUE TITLE
UI suggestion: Bring the filter out on the "Exam results" tab, even before the search

### ISSUE THREAD

**Issue by leelightman** [gcivil-nyu-org/nycCivilServiceJobs#137]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

I think it will be more clear to have the filter out as soon as the "Exam results" page is opened.

## Steps to Reproduce

1.
2.
3.
4.

**Comment by gauravag2207** [comment]
Hi @leelightman , We can't have filters beforehand as we only show results after the search.

**Comment by shivangpandya** [comment]
As Gaurav mentioned, this is working as intended, as we don't want to filter results before the search results appears
