### ISSUE TITLE
Duplicate: Duplicate values in Agency Drop down filter #126

### ISSUE THREAD

**Issue by gururaj3** [gcivil-nyu-org/nycCivilServiceJobs#138]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

This issue is already pointed out be Katie. The issue is already pointed out #126 

## Steps to Reproduce

1.
2.
3.
4.

**Comment by gauravag2207** [comment]
As mentioned in the issue description, its a duplicate

**Comment by joshganguly** [comment]
@gururaj3 please track this via #126 . Closing this
