### ISSUE TITLE
show something on Exam Results page before the first search

### ISSUE THREAD

**Issue by jackxujh** [gcivil-nyu-org/nycCivilServiceJobs#140]
unlike other pages of the site which are more straightforward, I didn't know what I could search to see something in the exam results page, without trying some random things, or referring to the guide from the team.

I suggest automatically showing some Recent Published Results, or Recent Results of Your Followed Exams on the page as a starter. so it not only gives people some sense what they could search, but also show information that might be useful. after all, those information are posted publicly.

**Comment by gauravag2207** [comment]
Great suggestion @jackxujh . We will certainly take your suggestions and look into what we can do.

**Comment by i-rahman** [comment]
@jackxujh, we have added Recently Released Exam Cards on the Exam Result Page. Please take a look.
