### ISSUE TITLE
real time or more responsive subscription alerts

### ISSUE THREAD

**Issue by jackxujh** [gcivil-nyu-org/nycCivilServiceJobs#141]
I was not able to make the 7:30 round of subscription updates. so I could not see anything changed after I modify my subscriptions. I am not sure if this is a constraint on Heroku or the architecture of the project, but it could be helpful if the subscription matching is more frequent.

**Comment by gauravag2207** [comment]
Hi Jack,

7.30 was a manual run only for testing purposes. In real-time, this would run every morning and notify users based on their subscription.

We decided for once per day as we thought users might not like if we spam them with multiple emails per day. But we can certainly increase the frequency if you think we should.
Thanks,
Gaurav

**Comment by i-rahman** [comment]
@jackxujh we are actually using a Dyno to run "python scripts/runapscheduler.py" and it is a paid dyno. We pay for each run.

**Comment by jackxujh** [comment]
@gauravag2207 @i-rahman thank you for the explanation and I now understand how it works under the hood. so it is a limitation of Heroku, that's okay. 

if you agree, I can close this issue.

**Comment by i-rahman** [comment]
@jackxujh yes we agree. Due to the addtional cost associated with running the dyno for schedular, we have it set to limited usage.

**Comment by jackxujh** [comment]
okay, closing it now
