### ISSUE TITLE
BUG: Able to create account completely with numbers

### ISSUE THREAD

**Issue by gururaj3** [gcivil-nyu-org/nycCivilServiceJobs#143]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

Able to create an account by entering only numbers for Username, firstname, lastname

## Expected Behavior

Should not be able to create an account if the user enters only numbers

## Current Behavior

I can create an account by entering only the numbers

## Steps to Reproduce

1.
2.
3.
4.

**Comment by joshganguly** [comment]
duplicate of #135

**Comment by gauravag2207** [comment]
Hi @gururaj3 ,

I personally don't think this is a bug. There's nothing wrong with having numbers in name and user.

Thanks,
Gaurav

**Comment by shivangpandya** [comment]
Working as intended
