### ISSUE TITLE
Add Activity Diagram for Sign In / Register Epic

### ISSUE THREAD

**Issue by gsavitha** [gcivil-nyu-org/nycCivilServiceJobs#16]
Acceptance Criteria: 
- Activity Diagram is Created to encompass all the User Stories for Sign In / Register Epic

Definition of Done:
Activity Diagram is Reviewed by Team
Activity Diagram is added to Presentation

**Comment by i-rahman** [comment]
![SE project - PPT Activity Diagram](https://user-images.githubusercontent.com/30580940/94743775-f00de000-0345-11eb-8921-39fdbd122a62.png)

**Comment by i-rahman** [comment]
Closing Issue Diagram has been added to the Presentation as well
