### ISSUE TITLE
Add user stories for Register/Sign In Epic in Zenhub.

### ISSUE THREAD

**Issue by gsavitha** [gcivil-nyu-org/nycCivilServiceJobs#17]
**Acceptance Criteria:**
- Work on and add User Story for  "As an unregistered user, I want to create an account, so that I am able to have a personalized user experience"
- Work on and add User Story for "As a Job Seeker, I want to receive a verification email from nycCivilService after Successful Account creation, so that I am able to verify being the owner of the account."
- Work on and add User Story for "As Hiring Manager, I want to receive a verification email from nycCivilService after account approval, so that I am able to verify being the owner of the account."
- Work on and User Story for "As a registered Job seeker / Hiring Manager, I want to login to the application, so that I am able to see to my personalized home page."
- Work on and User Story for "As a registered Job seeker / Hiring Manager, I want to be able to recover the password to my account, so that I will be able to access my account in case I forgot the password."

**Definition of Done:**
All the user stories are reviewed added to Zenhub and Tagged to the Epic for it

**Comment by gauravag2207** [comment]
Added the User stories For Registered Job Seeker to Zenhub. (Issue #18 and Issue #19 )

**Comment by joshganguly** [comment]
Added the User stories for `Hiring Manager` to Zenhub. (Issue #20 )

**Comment by shivangpandya** [comment]
Added user stories for Unregistered User and Jobseeker( Issue #21 and Issue #22 )
