### ISSUE TITLE
As a registered Job seeker / Hiring Manager, I want to be able to recover the password to my account so that I will be able to access my account in case I forgot the password.

### ISSUE THREAD

**Issue by gauravag2207** [gcivil-nyu-org/nycCivilServiceJobs#19]
**User story**
As a registered Job seeker / Hiring Manager, I want to be able to recover the password to my account so that I will be able to access my account in case I forgot the password.

**Acceptance criteria**
- [x] Provide Forgot Password Link on Sign in Page
- [x] Validate Credentials by entering email address and requesting a reset password link
- [x] If email address exists in DB, then a reset password link will be sent
- [x] Once clicked on the link, redirect to the default reset password page in django
- [x] Able to reset password successfully

**Definition of Done**
- [x] Passed Unit Testing 
- [x] Code Review Completed 
- [x] Passed peer testing based on AC
- [x] Change Deployed to Production
- [x] Validated as working in Production

**Comment by gauravag2207** [comment]
In addition to the above story, update the user data model to incorporate the extra fields-
Account Type
Date Of Birth

**Comment by i-rahman** [comment]
Code has been Reviewed by @gauravag2207. Still need to be deployed to STG and PROD.
