### ISSUE TITLE
Epic Names do not match the context diagram

### ISSUE THREAD

**Issue by gcivil-nyu** [gcivil-nyu-org/nycCivilServiceJobs#2]
Looking at the context diagram, https://github.com/gcivil-nyu-org/nycCivilServiceJobs/wiki/High-Level-Context-Analysis the epic names in the bubbles do not match the epic names described in the text,
Please fix.

**Comment by joshganguly** [comment]
We had missed one epic. Have added it to the [High Level Context Analysis](https://github.com/gcivil-nyu-org/nycCivilServiceJobs/wiki/High-Level-Context-Analysis) wiki under the Epics section. Also changed some of the words and their order to match the diagram.
