### ISSUE TITLE
As an unregistered user, I want to create an account, so that I am able to have a personalized user experience.

### ISSUE THREAD

**Issue by shivangpandya** [gcivil-nyu-org/nycCivilServiceJobs#21]
**User story**
As an unregistered user, I want to create an account, so that I am able to have a personalized user experience.

**Acceptance criteria**
- [x] 1.Set up the environment for development
- [x] 2.There is a Preliminary Landing Page for the web-site with a banner containing ‘nycCivilServiceJobs’ as the title and Sign In link
- [x] 3.Sign In Page has a link to Create An Account
- [x] 4.Account Creation page is a HTML form consisting of the following required fields:
  - Account Type (Dropdown) - [Job Seeker / Hiring Manager]  
  - First Name (Text box)
  - Last Name (Text box)
  - Date of Birth (date field - mm/dd/yy)
  - Username(Text box)
  - Email (Text box) [must be ".gov" for Hiring Manager]
  - Password (Text box) - [Django's default password contraints]
  - Re-enter Password (Text box)
  - Security Question and Answer field (Open Text Box)
  - Register button (link)
- [x] 5.Display Error Alert when Password do not meet criteria or non-matching entries in Password and Re-enter Password fields
- [x] 6.Appropriate Confirmation Pages displayed to Users (Job Seeker/Hiring Manager Role)
- [x] 7.Add Error Page for unexpected Error “Error in Account Creation. Please contact the Support” 

**Definition of Done**
- [x] Passed Unit Testing 
- [x]  Code Review Completed 
- [x]  Passed peer testing based on AC
- [x]  Change Deployed to Production
- [x]  Validated as working in Production

**Comment by i-rahman** [comment]
Validated all features as working in Production.
