### ISSUE TITLE
As a Job Seeker/Hiring Manager, I want to receive a confirmation email from nycCivilService after Successful Account creation, so that I am able to verify being the owner of the account

### ISSUE THREAD

**Issue by shivangpandya** [gcivil-nyu-org/nycCivilServiceJobs#22]
**User story**
As a Job Seeker/Hiring Manager, I want to receive a confirmation email from nycCivilService after Successful Account creation, so that I am able to confirm being the owner of the account.

**Acceptance criteria**
- [x]  Database is triggered for sending confirmation Email 
- [x] User receives Job Seeker after successful account creation

**Definition of Done**
- [x]  Passed Unit Testing 
- [x] Code Review Completed 
- [x] Passed peer testing based on AC
- [x] Change Deployed to Production
- [x] Validated as working in Production

**Comment by i-rahman** [comment]
Validated all features as working in Production
