### ISSUE TITLE
Upload High Level  Design Diagrams on wiki

### ISSUE THREAD

**Issue by shivangpandya** [gcivil-nyu-org/nycCivilServiceJobs#23]

**Comment by gauravag2207** [comment]
Added the below 2 UML diagrams to the [High Level Design ](https://github.com/gcivil-nyu-org/nycCivilServiceJobs/wiki/High-Level-Design) Wiki page.
1) Registration and Verification
2) Search for Exams & Jobs

**Comment by shivangpandya** [comment]
Added the below  UML diagrams to the [High Level Design ](https://github.com/gcivil-nyu-org/nycCivilServiceJobs/wiki/High-Level-Design) Wiki page.
1) Personalized Dashboard

**Comment by joshganguly** [comment]
Added the below UML diagram to the [High Level Design Wiki page](https://github.com/gcivil-nyu-org/nycCivilServiceJobs/wiki/High-Level-Design)

Update, Notify and Subscribe

**Comment by gsavitha** [comment]
Added the User Login UML diagram to the [High Level Design Wiki page](https://github.com/gcivil-nyu-org/nycCivilServiceJobs/wiki/High-Level-Design)

**Comment by joshganguly** [comment]
@gsavitha and @i-rahman  have made their changes already. Have reviewed this final Wiki after making my changes. Closing the Issue.
