### ISSUE TITLE
As a Data Source/Server, I want to update Jobs in real-time, so that users have reliable access to the latest job postings from NYC Open Dataset.

### ISSUE THREAD

**Issue by i-rahman** [gcivil-nyu-org/nycCivilServiceJobs#24]
**User Story**: 
As a Data Source/Server, I want to update Jobs in real-time, so that users have reliable access to the latest job postings from NYC Open Dataset.

**Acceptance Criteria**:

- [x] Back-end Tables and Schemas have been set up (Set up Models for Job Posting)
- [x] The server runs a cron job once daily to call the API and fetch the latest job postings
- [x] The server updates the database with the latest information successfully

**Definition of Done:**

- [x] Pass Unit Testing
- [x] Pass Code Review
- [x] Meet AC
- [x] Deploy change to Production Successfully

**Comment by gauravag2207** [comment]
Gaurav - Would start building the Database Models.
Shivang - Would work on the API call to bring in the data, preprocess it, and save it to the database.

**Comment by gauravag2207** [comment]
The feature is implemented
