### ISSUE TITLE
As a Data Source/Server, I want to update Exam Results in real-time, so that the users have reliable access to the latest Exam Results from NYC Open Dataset

### ISSUE THREAD

**Issue by i-rahman** [gcivil-nyu-org/nycCivilServiceJobs#25]
**User Story** 
As a Data Source/Server, I want to update Exam Results in real-time, so that the users have reliable access to the latest Exam Results from NYC Open Dataset.

**Acceptance Criteria**

- [x] Back-end Tables and Schemas have been set up (Set up Models for Exam Results)
- [x] The server runs a cron job once daily to call the API and fetch the latest Exam Results 
- [x] The server updates the database with the latest information successfully

**Definition of Done**

- [x] Pass Unit Testing
- [x] Pass Code Review
- [x] Meet AC
- [x] Deploy to Production 
- [x] Validate as working in Production

**Comment by gauravag2207** [comment]
Iffat - Would start building the Database Models.
Savitha - Would work on the API call to bring in the data, preprocess it, and save it to the database.
