### ISSUE TITLE
Technical - Optimize the Search for Exam Result 

### ISSUE THREAD

**Issue by i-rahman** [gcivil-nyu-org/nycCivilServiceJobs#89]
**Acceptance Criteria**:
- [x] Search for exam result data table filter and search is significantly faster on Heroku PROD
- [x] "Processing" text on the datatable should not appear on loading Exam result page unless search is initiated on landing page

**Definition of Done**
- [x] Passed Unit Test
- [x] Passed Code Review
- [x] Successfully deployed to Staging and Validate as working
- [ ] Successfully deployed to Production and Validate as working

**Comment by joshganguly** [comment]
this tracked and implemented as a part of #140
